"""empty message

Revision ID: c0880c82eee8
Revises: a027b5efb520
Create Date: 2024-02-15 13:11:00.276154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0880c82eee8'
down_revision = 'a027b5efb520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=150), nullable=False))
    op.add_column('book', sa.Column('isbn', sa.String(length=30), nullable=True))
    op.add_column('book', sa.Column('author_name', sa.String(length=100), nullable=True))
    op.add_column('book', sa.Column('length', sa.String(length=15), nullable=True))
    op.add_column('book', sa.Column('cover', sa.String(length=25), nullable=True))
    op.drop_column('book', 'email')
    op.drop_column('book', 'address')
    op.drop_column('book', 'name')
    op.drop_column('book', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('book', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('book', 'cover')
    op.drop_column('book', 'length')
    op.drop_column('book', 'author_name')
    op.drop_column('book', 'isbn')
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
